### ISSUE TITLE
Problem with countour

### ISSUE THREAD

**Issue by ribery77** [LastTheory/FourierAnimation#1]
Hi I am not familiar with opencv. Would you like to give me an example how from image I can get contour = <your n x 2 array of ordered (x, y) contour points>? I mean I am not sure about this. Can you provide a toy example please?

**Comment by LastTheory** [comment]
There are two approaches:

1. Use OpenCV. The idea is use some image processing techniques such as edge detection and/or thresholding to obtain a clear isolation of the relevant boundaries. Then calling cv2.findContours() function which returns the points in order around a contour for each contour in the image. A toy example is below:
```
im = cv2.imread('heart.png')
contours, hierarchy = cv2.findContours(cv2.cvtColor(im.copy(), cv2.COLOR_BGR2GRAY), cv2.RETR_TREE, cv2.CHAIN_APPROX_NONE)
#after drawing contours on image and inspecting ones retrieved, select the relevant one
contour = np.squeeze(contours[1])
c, nlist = fa.calculateFourierSeries(contour, nvec=10)
fa.animate(c, nlist, (im.shape[0], im.shape[1]), save=False)
```

2. Use image software like Paint or Photoshop to manually go around a contour and note down point coordinates. The more dense the coordinates, the better the contour.

<img width="750" alt="heart" src="https://user-images.githubusercontent.com/53421283/62234031-aced6100-b37e-11e9-9300-3ec824556c36.png">

**Comment by ribery77** [comment]
Thanks. Let me try to reproduce it.

**Comment by ribery77** [comment]
Thanks it works. One peculiar question is it kind of slow to draw images. Is it possible that this issue is from my PC.

**Comment by ribery77** [comment]
Hi. If I have a image with face how I need to preprocess in way that you showed on youtube video?

**Comment by LastTheory** [comment]
> Thanks it works. One peculiar question is it kind of slow to draw images. Is it possible that this issue is from my PC.

Some things that might speed it up are the arguments to the animate method: turn drawArrows=False, turn drawCircles=False, lower ptdensity. Also you can lower nt which controls total number of frames and resize down the input image. For me, it usually took 2-10 minutes for a 30 second video.


> Hi. If I have a image with face how I need to preprocess in way that you showed on youtube video?

I manually outlined the points I wanted for that one. You could try messing with Canny edge detection and thresholding and see if findContours gives you good results or not.

**Comment by ribery77** [comment]
Thanks a lot. Kudos for your job.

**Comment by LastTheory** [comment]
No problem! Also forgot to mention it speeds up if you don't display the video as processing (display argument in animate). Good luck
