### ISSUE TITLE
ask for advice

### ISSUE THREAD

**Issue by zcdliuwei** [LastTheory/FourierAnimation#2]
Hello, I'm very interested in your work. What a wonderful display !!
Personally, Fourier seems to imitate the process of human painting, and all the examples you show can be drawn with one stroke.
I would like to ask if Fourier supports multiple strokes.
Suppose there are two butterflies in the original PNG image, or there are multiple paths in my SVG file,
I want to draw two butterflies with two strokes, because if one stroke is used, there will be a big jump between the two targets，
And even if there is only one target or path, I also want to use multiple strokes in order to simplify and not cause a lot of jumping details,
So in general, my question is how to control Fourier drawing so that it can support user-defined stroke number？
I'm looking forward to your answer，Thank you very much。

**Comment by LastTheory** [comment]
I just added a new update that allows you to do this. 

To draw multiple contours in a single stroke without the connecting curves, you can now pass a contour list to draw each one. This draws all the contours as one periodic function. 

To draw a stroke for each contour, simple run the functions in a loop where after the first iteration, the following iterations use the frame returned by the previous animate function passed in again to the current one through start_frame argument. Using the same video writer for each iteration will combine them all into one video. This draws each contour as its own periodic function.

Hope it helps!

**Comment by zcdliuwei** [comment]
> I just added a new update that allows you to do this.
> 
> To draw multiple contours in a single stroke without the connecting curves, you can now pass a contour list to draw each one. This draws all the contours as one periodic function.
> 
> To draw a stroke for each contour, simple run the functions in a loop where after the first iteration, the following iterations use the frame returned by the previous animate function passed in again to the current one through start_frame argument. Using the same video writer for each iteration will combine them all into one video. This draws each contour as its own periodic function.
> 
> Hope it helps!

Thank you for your reply, very helpful！
Now I have another difficult problem: when I use multiple strokes to draw multiple paths and reduce the number of circles in each path to simplify the path, two paths that originally did not intersect may intersect after simplification, which will affect the beauty of the result。
I have no idea to solve this problem. I hope I can get your advice. Thank you very much, have a nice day!

**Comment by LastTheory** [comment]
The Fourier series is an approximation after all, so the primary way to increase the accuracy of the contours would be to increase the number of components (nvec) so that the objects are better represented. Additionally, you can represent each object as its own periodic function (described above as method for multiple strokes) so that the components calculated for the contours are dedicated to each object instead of shared across multiple.

**Comment by zcdliuwei** [comment]
> The Fourier series is an approximation after all, so the primary way to increase the accuracy of the contours would be to increase the number of components (nvec) so that the objects are better represented. Additionally, you can represent each object as its own periodic function (described above as method for multiple strokes) so that the components calculated for the contours are dedicated to each object instead of shared across multiple.

My goal is not to improve the accuracy of representation, on the contrary, I want to simplify the path, trying to simplify the path from the original image by reducing the number of circles of a path, and try to ensure that the final image is as beautiful as possible。
For example, I have a PNG image with a face inside. I get the contour of eyes and nose through some edge detection algorithms，I want to draw the eyes and nose separately with two strokes. At the same time, each stroke reduces the number of circles. The eyes and nose in the original PNG image are not intersected, but by reducing the number of circles, the two paths of eyes and nose may intersect.
I have no idea to solve this problem. I hope I can get your advice. Thank you very much, have a nice day!

**Comment by LastTheory** [comment]
Not sure. Best guess would be to look at the Fourier coefficients returned and play around with zeroing out some percentage of them. Even with a higher number of coefficients returned, you could end up utilizing less total components overall, and it may give a different contour approximation that is more along what you are looking for.

**Comment by zcdliuwei** [comment]
> Not sure. Best guess would be to look at the Fourier coefficients returned and play around with zeroing out some percentage of them. Even with a higher number of coefficients returned, you could end up utilizing less total components overall, and it may give a different contour approximation that is more along what you are looking for.

I'll think about it carefully. If you have any better suggestions, please let me know， thank you very much
